; None of the configuration options below are optional
[proxy]
listen_address=192.168.100.1
tftpd=192.168.100.1
#interface=virbr1
filename=undionly.kpxe
filename_efi32=ipxe32.efi
filename_efi64=ipxe.efi
vendor_specific_information="proxyDHCPd"
